<a href="https://colab.research.google.com/github/arfinmahmudshiblu/Image-Video-Processing-with-OpenCV/blob/main/Pretrained_models_in_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import preprocess_input, decode_predictions
import numpy as np

In [2]:
model = ResNet50(weights='imagenet')

102967424/102967424 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


# Dog Detection

In [3]:
img_path = '/content/dog.jfif'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

In [5]:
x

array([[[[ -50.939003,  -38.779   ,  -71.68    ],
         [ -50.939003,  -36.779   ,  -69.68    ],
         [ -47.939003,  -29.779   ,  -63.68    ],
         ...,
         [ -98.939   ,  -97.779   , -115.68    ],
         [ -93.939   , -103.779   , -112.68    ],
         [ -94.939   , -104.779   , -113.68    ]],

        [[ -48.939003,  -36.779   ,  -69.68    ],
         [ -48.939003,  -34.779   ,  -67.68    ],
         [ -45.939003,  -27.779   ,  -61.68    ],
         ...,
         [ -95.939   ,  -94.779   , -112.68    ],
         [ -93.939   , -103.779   , -112.68    ],
         [ -93.939   , -103.779   , -112.68    ]],

        [[ -46.939003,  -34.779   ,  -67.68    ],
         [ -46.939003,  -32.779   ,  -65.68    ],
         [ -42.939003,  -24.779   ,  -58.68    ],
         ...,
         [ -90.939   ,  -92.779   , -109.68    ],
         [ -90.939   , -102.779   , -113.68    ],
         [ -90.939   , -102.779   , -113.68    ]],

        ...,

        [[ -62.939003,  -24.779   ,   

In [4]:
preds = model.predict(x)
print('Predicted:', decode_predictions(preds, top=3)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step
35363/35363 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Predicted: [('n02099601', 'golden_retriever', np.float32(0.9953039)), ('n02104029', 'kuvasz', np.float32(0.0007018874)), ('n02100877', 'Irish_setter', np.float32(0.00066082197))]


# Cat Detection

In [9]:
img_path = '/content/cat.jfif'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

In [10]:
x

array([[[[ 15.060997 ,  -0.7789993, -15.68     ],
         [ 21.060997 ,   4.2210007,  -7.6800003],
         [ 43.060997 ,  22.221    ,   8.32     ],
         ...,
         [ 83.061    ,  57.221    ,  36.32     ],
         [ 76.061    ,  52.221    ,  31.32     ],
         [ 66.061    ,  39.221    ,  20.32     ]],

        [[ 29.060997 ,  13.221001 ,  -1.6800003],
         [ 28.060997 ,  11.221001 ,  -0.6800003],
         [ 38.060997 ,  17.221    ,   3.3199997],
         ...,
         [ 86.061    ,  60.221    ,  39.32     ],
         [ 77.061    ,  53.221    ,  32.32     ],
         [ 67.061    ,  39.221    ,  23.32     ]],

        [[ 31.060997 ,  15.221001 ,   4.3199997],
         [ 23.060997 ,   7.2210007,  -4.6800003],
         [ 40.060997 ,  19.221    ,   5.3199997],
         ...,
         [ 87.061    ,  61.221    ,  40.32     ],
         [ 77.061    ,  51.221    ,  30.32     ],
         [ 73.061    ,  44.221    ,  25.32     ]],

        ...,

        [[107.061    ,  87.221    ,  7

In [11]:
preds = model.predict(x)
print('Predicted:', decode_predictions(preds, top=3)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
Predicted: [('n02124075', 'Egyptian_cat', np.float32(0.5920725)), ('n02123159', 'tiger_cat', np.float32(0.27007812)), ('n02123045', 'tabby', np.float32(0.087492))]


# Sports Car Detection

In [12]:
img_path = '/content/sportscar.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

In [13]:
x

array([[[[-25.939003  ,  10.221001  ,  11.32      ],
         [-29.939003  ,   6.2210007 ,   7.3199997 ],
         [-25.939003  ,  10.221001  ,  11.32      ],
         ...,
         [-34.939003  ,  11.221001  ,   0.3199997 ],
         [-21.939003  ,  24.221     ,  13.32      ],
         [-22.939003  ,  22.221     ,  14.32      ]],

        [[-31.939003  ,   7.2210007 ,   6.3199997 ],
         [-37.939003  ,   1.2210007 ,   0.3199997 ],
         [-31.939003  ,   7.2210007 ,   6.3199997 ],
         ...,
         [-33.939003  ,  12.221001  ,   1.3199997 ],
         [-28.939003  ,  17.221     ,   6.3199997 ],
         [-27.939003  ,  16.221     ,   8.32      ]],

        [[-38.939003  ,   0.22100067,  -0.6800003 ],
         [-37.939003  ,   4.2210007 ,   0.3199997 ],
         [-34.939003  ,   7.2210007 ,   3.3199997 ],
         ...,
         [-32.939003  ,  13.221001  ,   2.3199997 ],
         [-32.939003  ,  13.221001  ,   2.3199997 ],
         [-32.939003  ,  11.221001  ,   3.3199997 ]],

In [14]:
preds = model.predict(x)
print('Predicted:', decode_predictions(preds, top=3)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
Predicted: [('n04285008', 'sports_car', np.float32(0.97711515)), ('n04037443', 'racer', np.float32(0.019544007)), ('n02974003', 'car_wheel', np.float32(0.0017484576))]
